Use auto_enable_organization_members to enroll existing accounts
aws-samples/amazon-guardduty-for-aws-organizations-with-terraform pull request #9
Opened 2024-07-31 10:15 UTC by gps035

*Description of changes:*

Switches `auto_enable = true` to `auto_enable_organization_members = "ALL"`, and removes terraform for adding guardduty members. 

The [original argument is now deprecated](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_organization_configuration#auto_enable), which this resolves. This change means that guard duty will be enabled across existing organisation members as before but the [API documentation](https://docs.aws.amazon.com/guardduty/latest/APIReference/API_UpdateOrganizationConfiguration.html) states that this will occur within 24 hours, which might be considered a change in behaviour.

This option in the API seems to be something that was [introduced in August 2023](https://aws.amazon.com/about-aws/whats-new/2023/08/amazon-guardduty-multi-account-management/)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-03 05:21 UTC, avanbecelaere requested changes

2024-08-03 05:21 UTC, avanbecelaere commented on enable-gd/modules/guardduty-baseline/README.md
Can you remove this terraform-docs file from the PR? We aren't currently using these files for the rest of our tf code. If you would like to see this added everywhere, please create an issue and a new PR for all tf files.

2024-08-03 05:21 UTC, avanbecelaere commented on enable-gd/modules/guardduty-baseline/main.tf
What aws provider version did you use to test these changes? The version config will need to be updated as well or the deployment will fail using the current version with these changes.

I was able to test successfully with the latest (5.61.0).

2024-08-03 14:51 UTC, gps035 commented on enable-gd/modules/guardduty-baseline/README.md
Happy to remove those but they were created by the pre-commit hook configured here https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform/blob/main/.pre-commit-config.yaml#L6

I assumed this is what was intended by `Ensure local tests pass` in the contributing guidelines so I installed the hooks, maybe that should be removed as well. 

I'll be in a position to update the branch on Monday

2024-08-03 14:59 UTC, gps035 commented on enable-gd/modules/guardduty-baseline/main.tf
Very good point. I only noticed while adapting the code into something more suited to our use case, so I would have been testing against a very recent version, I'll have to check later.

The deprecation happened in [v5.0.0](https://github.com/hashicorp/terraform-provider-aws/pull/30736#issuecomment-1511643324). Currently this module specifically expects 3.74.0. Not sure how you'd like to manage this. Perhaps it would be best to uplift versions across the board to the latest major since it reads like something intended to be applied once from a local machine, maybe best to drop this.

2024-08-05 08:58 UTC, gps035 commented on enable-gd/modules/guardduty-baseline/main.tf
5.60.0 is the version I had tested against. For now I've updated the required provider specified in the parent module, although that does differ from the other modules now

2024-08-05 08:58 UTC, gps035 commented on enable-gd/modules/guardduty-baseline/README.md
Removed the readme

2024-08-07 16:24 UTC, avanbecelaere commented on enable-gd/modules/guardduty-baseline/main.tf
@gps035 , did you find in your testing that:

1. GuardDuty does not get automatically enabled in the organization management account 
2. GuardDuty is enabled in the log archive account, but an invitation has not been sent/accepted?

2024-08-07 17:02 UTC, avanbecelaere commented on enable-gd/modules/guardduty-baseline/README.md
I ran a pre-commit on all tf files and updated main. can you merge main into your branch and add your terraform-docs file back in with the proper updates?

2024-09-30 07:55 UTC, gps035 commented on enable-gd/modules/guardduty-baseline/main.tf
Sorry for the delay. I believe we did notice `1`, and it's something that we raised with our TAM when we realised. This wasn't a deal breaker for us though, since we expected to retain strict control over any provisioning in the management account. At the time, I wasn't sure if this should be considered a bug in the AWS service.

I wasn't aware of the second point however. I have since left the team so it's not something I can check, but I think I was aware of the account not having GuardDuty enabled. It made sense that this would happen to me as the existing terraform explicitly does not enable GD in the delegated admin account, presumably to work around a problem that occurs when enabled there. Seeing this also made me assume that there's a reason for it to not be enabled in the management account.

2024-11-07 04:05 UTC, avanbecelaere approved these changes

2024-11-07 04:09 UTC, merged